### ISSUE TITLE
Access to _G in lua macros

### ISSUE THREAD

**Issue by GlowingUmbreon** [d0sboots/perfect-tower#7]
Currently it is not possible to share lua macro variables across scripts. Allowing access to _G (or making it work across scripts) will fix this issue Example:
Script1
```lua
{lua(\
_G.pie = "Dog" \
)}
```
Script2
```lua
{lua(\
print(_G.pie)\
)}
```
Another potential fix to this issue would be to allow importing another script, this could be cleaner but would possibly be more complex to implement, example:
Lib
```lua
#collapse(expr) {lua(return {expr})}
```
Main
```lua
import Lib
collapse(4 * 4)
```

**Comment by d0sboots** [comment]
Access to global state across scripts is intentionally disallowed, because it would be non-deterministic: In your example, how would you determine that Script1 runs before Script2, instead of the other way around? Also, it would lead to bugs, because by having a persistent global state, stuff would clutter the globals from compile to compile, meaning that your results when making multiple changes would not be the same (necessarily) as after a fresh load of the editor.

Instead, every script has a fresh global state that lasts only as long as the compile, and :import is already implemented and available for use. (Check the help on a fresh load.)

**Comment by GlowingUmbreon** [comment]
> Access to global state across scripts is intentionally disallowed, because it would be non-deterministic: In your example, how would you determine that Script1 runs before Script2, instead of the other way around? Also, it would lead to bugs, because by having a persistent global state, stuff would clutter the globals from compile to compile, meaning that your results when making multiple changes would not be the same (necessarily) as after a fresh load of the editor.
> 
> Instead, every script has a fresh global state that lasts only as long as the compile, and :import is already implemented and available for use. (Check the help on a fresh load.)

Ah, the help screen cannot be scrolled when it is first loaded which is why I never noticed that, thanks for letting me know.

**Comment by d0sboots** [comment]
Can you elaborate on that a little? I can scroll the help screen, and it should be scrollable, so if you can't then that indicates a (separate) bug.
